print('===DESAFIO 09===')
t = float(input('Digite um valor para saber a tabuada: '))
print(f'O valor {t} multiplicado 1 vez é: {t*1}')
print(f'O valor {t} multiplicado 2 vezes é: {t*2}')
print(f'O valor {t} multiplicado 3 vezes é: {t*3}')
print(f'O valor {t} multiplicado 4 vezes é: {t*4}')
print(f'O valor {t} multiplicado 5 vezes é: {t*5}')
print(f'O valor {t} multiplicado 6 vezes é: {t*6}')
print(f'O valor {t} multiplicado 7 vezes é: {t*7}')
print(f'O valor {t} multiplicado 8 vezes é: {t*8}')
print(f'O valor {t} multiplicado 9 vezes é: {t*9}')
print(f'O valor {t} multiplicado 10 vezes é: {t*10}')
