print('===DESAFIO 04===')
o = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(o))
print('Só tem espaço? ', o.isspace())
print('É um número? ', o.isnumeric())
print('É alfabético? ', o.isalpha())
print('É alfanúmerico? ', o.isalnum())
print('Está em maiúsculas? ', o.isupper())
print('Está me minúsculas? ', o.islower())
print('Está capitalizada? ', o.istitle())
