print('===DESAFIO 08===')
print('Conversão de metros para centímetros e milímetros.')
n1 = float(input('Digite o valor: '))
print(f'O valor {n1} em metros equivale á: {n1*100} centímetros.')
print(f'O valor {n1} em metros equivale á: {n1*1000} milímetros.')
print(f'O valor {n1} em metros equivale á: {n1/1000} quilômetros.')
print(f'O valor {n1} em metros equivale á: {n1*10} decímetros.')
print(f'O valor {n1} em metros equivale á: {n1/10} decâmetros.')
print(f'O valor {n1} em metros equivale á: {n1/100} hectametros.')
