print('===DESAFIO 022===')
nome = str(input('Qual o seu nome todo? ')).strip()
print('Analisando seu nome...')
print('Seu nome todo maíusculo fica: ', nome.upper())
print('Seu nome todo mínusculo fica: ', nome.lower())
print(f'O seu nome contém o total de {len(nome) - nome.count(" ")} letras!')
#print(f'O seu primeiro nome tem {nome.find(" ")}')
separa = nome.split()
print(f'O seu primeiro nome é {separa[0]} e tem {len(separa[0])} letras.')
